version: '3'

services:

    rabbitmq:
        image: rabbitmq:3.8-management
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        networks:
            - private

    loadbalancer:
        image: nginx:1.17.8-alpine
        volumes:
            - ./docker/nginx/loadbalancer.conf:/etc/nginx/conf.d/default.conf
        networks:
            - private
        depends_on:
            - api-web
            - tip-web

    php-fpm:
        build:
            context: docker/php
            args:
                PUID: ${PUID}
        volumes:
            - ./.composer/:/.composer
            - ./em2021-api/:/data-api/
            - ./tips/:/data-tips/
            - ./match/:/data-match/
            - ./match-api/:/data-match-api/
        networks:
            - default
            - private
            - api
            - tip
            - match
        environment:
            - APP_ENV=docker
        depends_on:
            - rabbitmq

    api-db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: admin
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - api

    api-redis:
        image: redis:6
        command: redis-server --appendonly yes
        volumes:
            - redis-data-api:/data
        networks:
            - api

    api-web:
        image: nginx:1.17.8-alpine
        volumes:
            - ./em2021-api/:/data-api/
            - ./docker/nginx/vhost-api.conf:/etc/nginx/conf.d/default.conf
        networks:
            api:
            private:
                aliases:
                    - web.api
        depends_on:
            - api-db
            - api-redis
            - php-fpm

    tip-redis:
        image: redis:6
        command: redis-server --appendonly yes
        volumes:
            - redis-data-tip:/data
        networks:
            - tip

    tip-web:
        image: nginx:1.17.8-alpine
        volumes:
            - ./tips/:/data-tips/
            - ./docker/nginx/vhost-tips.conf:/etc/nginx/conf.d/default.conf
        networks:
            tip:
            private:
                aliases:
                    - web.tip
        depends_on:
            - tip-redis
            - php-fpm

    match-redis:
        image: redis:6
        command: redis-server --appendonly yes
        volumes:
            - redis-data-match:/data
        networks:
            - match

    match-web:
        image: nginx:1.17.8-alpine
        volumes:
            - ./match/:/data-match/
            - ./docker/nginx/vhost-match.conf:/etc/nginx/conf.d/default.conf
        networks:
            tip:
            private:
                aliases:
                    - web.match
        depends_on:
            - match-redis
            - php-fpm

volumes:
    rabbitmq-data:
    mysql-data:
    redis-data-api:
    redis-data-tip:
    redis-data-match:

networks:
    api:
    tip:
    match:
    private:
