version: '3'

services:

    rabbitmq:
        image: rabbitmq:3.8-management
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        networks:
            - private

    loadbalancer:
        image: nginx:1.17.8-alpine
        volumes:
            - ./docker/nginx/loadbalancer.conf:/etc/nginx/conf.d/default.conf
        networks:
            - private
        depends_on:
            - api-web
            - frontend-web

    php-fpm:
        build:
            context: docker/php
            args:
                PUID: ${PUID}
        volumes:
            - ./docker/php/custom-ini.ini:/usr/local/etc/php/conf.d/99-custom-ini.ini
            - ./.composer/:/.composer
            - ./em2021-api/:/data-api/
            - ./tips/:/data-tips/
            - ./match/:/data-match/
            - ./match-api/:/data-match-api/
            - ./frontend/:/data-frontend/
            - ./calculation-list/:/data-calculation-list/
            - ./ranking-list/:/data-ranking-list/
        networks:
            - default
            - private
            - api
            - tip
            - match
        environment:
            - APP_ENV=docker
            - PHP_MAX_EXECUTION_TIME=30
            - PHP_MEMORY_LIMIT=128M
        depends_on:
            - rabbitmq

    api-db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: admin
        volumes:
            - ./docker/mysql/custom-my.cnf:/etc/mysql/conf.d/99-custom-my.cnf
            - mysql-data:/var/lib/mysql
        networks:
            - api

    api-redis:
        image: redis:6
        command: redis-server --appendonly yes
        volumes:
            - redis-data-api:/data
        networks:
            - api

    api-web:
        image: nginx:1.17.8-alpine
        volumes:
            - ./em2021-api/:/data-api/
            - ./docker/nginx/vhost-api.conf:/etc/nginx/conf.d/default.conf
        networks:
            api:
            private:
                aliases:
                    - web.api
        depends_on:
            - api-db
            - api-redis
            - php-fpm

    tip-redis:
        image: redis:6
        command: redis-server --appendonly yes
        volumes:
            - redis-data-tip:/data
        networks:
            - tip

    match-redis:
        image: redis:6
        command: redis-server --appendonly yes
        volumes:
            - redis-data-match:/data
        networks:
            - match

    frontend-web:
        image: nginx:1.17.8-alpine
        volumes:
            - ./frontend/:/data-frontend/
            - ./docker/nginx/vhost-frontend.conf:/etc/nginx/conf.d/default.conf
        networks:
            private:
                aliases:
                    - web.frontend
        depends_on:
            - php-fpm

    ranking-list-redis:
        image: redis:6
        command: redis-server --appendonly yes
        volumes:
            - redis-data-ranking-list:/data
        networks:
            - ranking-list

    calculation-list-redis:
        image: redis:6
        command: redis-server --appendonly yes
        volumes:
            - redis-data-calculation-list:/data
        networks:
            - calculation-list

volumes:
    rabbitmq-data:
    mysql-data:
    redis-data-api:
    redis-data-tip:
    redis-data-match:
    redis-data-ranking-list:
    redis-data-calculation-list:

networks:
    api:
    tip:
    match:
    ranking-list:
    calculation-list:
    private:
