version: '3'

services:
  loadbalancer:
    ports:
      - 8080:8080
      - 8084:8084
  api-db:
    ports:
      - 3306:3306
  rabbitmq:
    ports:
      - 8088:15672
      - 5672:5672
  rediscommander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=api:api-redis,tip:tip-redis,match:match-redis,ranking-list:ranking-list-redis,calculation-list:calculation-list-redis
    depends_on:
      - api-redis
      - tip-redis
      - match-redis
      - calculation-list-redis
      - ranking-list-redis
    networks:
      - api
      - tip
      - match
      - calculation-list
      - ranking-list
    ports:
      - 8089:8081
   
