version: '3'

services:
  loadbalancer:
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 8084:8084
      - 8085:8085
      - 8086:8086
      - 8087:8087
      - 8088:8088
  rediscommander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=api:api-redis,tip:tip-redis,match:match-redis,ranking-list:ranking-list-redis,calculation-list:calculation-list-redis
    depends_on:
      - api-redis
      - tip-redis
      - match-redis
      - calculation-list-redis
      - ranking-list-redis
    networks:
      - api
      - tip
      - match
      - calculation-list
      - ranking-list
    ports:
      - 8089:8081
