version: '3'

services:
  loadbalancer:
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 8084:8084
      - 8085:8085
  rediscommander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=api:api-redis,tip:tip-redis,match:match-redis
    depends_on:
      - api-redis
      - tip-redis
      - match-redis
    networks:
      - api
      - tip
      - match
    ports:
      - 8086:8081
