version: '3'

services:
    rabbitmq:
        image: rabbitmq:3.8-management
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        networks:
            - private

    loadbalancer:
        image: nginx:1.17.8-alpine
        volumes:
            - ./docker/nginx/loadbalancer.conf:/etc/nginx/conf.d/default.conf
        networks:
            - private
        depends_on:
            - api-web

    api-db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: admin
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - api
    api-redis:
        image: redis:6
        command: redis-server --appendonly yes
        volumes:
            - redis-data-api:/data
        networks:
            - api

    php-fpm:
        build:
            context: docker/php
            args:
                PUID: ${PUID}
        volumes:
            - ./em2021-api/:/data-api/
            - ./tips/:/data-tips/
        networks:
            - default
            - private
            - api
            - tip
        environment:
            - APP_ENV=docker

    api-web:
        image: nginx:1.17.8-alpine
        volumes:
            - ./em2021-api/:/data-api/
            - ./docker/nginx/vhost-api.conf:/etc/nginx/conf.d/default.conf
        networks:
            api:
            private:
                aliases:
                    - web.api
        depends_on:
            - api-db
            - api-redis
            - php-fpm
            - rabbitmq

    redis_tip:
        image: redis:6
        command: redis-server --appendonly yes
        volumes:
            - redis-data-tip:/data

volumes:
    rabbitmq-data:
    mysql-data:
    redis-data-api:
    redis-data-tip:

networks:
    api:
    tip:
    private:
